Refactor linters and add name
vidsy/terraform-linter pull request #11
Opened 2019-02-27 16:53 UTC by stevenjack

### Problem

Needed more flexibility around running a set of linters for a given file as we may want to run multiple linters such as if resources and correct *and* name is in correct format.

### Solution

* Create `Linter` type for functions that can act like a linter.
* Refactor existing linters out of `lint_directory.go` into `linters.go`.
* Add `LintNames` as default linter then add more linters for each file type, then look over each and call function with config.

### Notes

- **Remember** to tag your merge commit after merging 👍
- **Remember** to add the Clubhouse ticket url as a comment ♣️ 🏠

2019-02-27 16:53 UTC, stevenjack commented
https://app.clubhouse.io/vidsy/story/6762

2019-02-27 17:06 UTC, revett commented on terraform/linter/linters.go
> +	return !strings.Contains(name, "-")
🏄 

Use a regex `a-z_`

2019-02-28 09:54 UTC, revett commented on terraform/linter/linters.go
> +	validNameRegex = `^[a-z0-9_]+$`
Can we extend it to not allow `_` as a prefix or suffix, and only allow a single `_` at a time.

Example: https://regex101.com/r/BeBFQx/1

2019-02-28 09:54 UTC, revett requested changes
Comment on regex

2019-02-28 10:45 UTC, revett approved these changes
🍰

2019-02-28 10:53 UTC, merged